server:
  port: 8085
  servlet:
    context-path: /oauth

spring:
  datasource:
    url: jdbc:mysql://hello-blog-mysql/inyaa?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: helloblog
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true